version: "3"

vars:
  PROTO_DIR: proto
  GEN_GO_DIR: gen/go

tasks:
  check-os:
    silent: true
    cmds:
      - |
        {{if eq OS "windows"}}
          echo "🪟 Windows detected? 🐧 sudo switch-to-linux --now!"
        {{end}}

  install-deps:
    desc: 🛠️ Install protobuf toolchain (protoc + Go plugins)
    deps: [check-os]
    silent: true
    cmds:
      - echo "📦 Checking dependencies..."
      - |
        if ! command -v protoc >/dev/null 2>&1;
        then
          echo "❌ Error: protoc not found."
          echo "👉 Install it with one of:"
          echo "   Arch:          sudo pacman -S protobuf"
          echo "   Ubuntu/Debian: sudo apt-get update && sudo apt-get install -y protobuf-compiler"
          echo "   macOS (brew):  brew install protobuf"
          exit 1
        fi
      - echo "✅ protoc found"
      - echo "⬇️  Installing Go plugins (protoc-gen-go, protoc-gen-go-grpc)..."
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - echo "🎉 All dependencies installed!"

  generate:
    desc: 🚀 Generate Go protobuf/grpc stubs for all .proto files
    deps: [install-deps]
    sources:
      - proto/**/*.proto
    generates:
      - gen/go/**/*.go
    silent: true
    cmds:
      - echo "🔨 Generating Go code from protos..."
      - mkdir -p "{{.GEN_GO_DIR}}"
      - |
        export PATH="$(go env GOPATH)/bin:$PATH"
        PROTO_FILES="$(find "{{.PROTO_DIR}}" -type f -name '*.proto' -print)"

        if [ -z "$PROTO_FILES" ]; then
          echo "⚠️  No .proto files found under '{{.PROTO_DIR}}'"
          exit 1
        fi

        protoc \
          -I "{{.PROTO_DIR}}" \
          --go_out="{{.GEN_GO_DIR}}" --go_opt=paths=source_relative \
          --go-grpc_out="{{.GEN_GO_DIR}}" --go-grpc_opt=paths=source_relative \
          $PROTO_FILES
      - echo "✨ Generation complete!"

  run-chat:
    desc: 💬 Run Chat Service
    cmds:
      - go run ./cmd/chat/main.go

  run-user:
    desc: 👤 Run User Service
    cmds:
      - go run ./cmd/user/main.go

  dev:
    desc: 🏃 Run both services in parallel
    deps: [run-chat, run-user]