// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package jwt

//go:generate minimock -i github.com/DaniilKalts/microservices-course-2023/7-week/pkg/jwt.Manager -o mock.go -n JWTManagerMock -p jwt

import (
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// JWTManagerMock implements Manager
type JWTManagerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAccessTokenTTL          func() (d1 time.Duration)
	funcAccessTokenTTLOrigin    string
	inspectFuncAccessTokenTTL   func()
	afterAccessTokenTTLCounter  uint64
	beforeAccessTokenTTLCounter uint64
	AccessTokenTTLMock          mJWTManagerMockAccessTokenTTL

	funcGenerateAccessToken          func(claims Claims) (s1 string, err error)
	funcGenerateAccessTokenOrigin    string
	inspectFuncGenerateAccessToken   func(claims Claims)
	afterGenerateAccessTokenCounter  uint64
	beforeGenerateAccessTokenCounter uint64
	GenerateAccessTokenMock          mJWTManagerMockGenerateAccessToken

	funcGenerateRefreshToken          func(claims Claims) (s1 string, err error)
	funcGenerateRefreshTokenOrigin    string
	inspectFuncGenerateRefreshToken   func(claims Claims)
	afterGenerateRefreshTokenCounter  uint64
	beforeGenerateRefreshTokenCounter uint64
	GenerateRefreshTokenMock          mJWTManagerMockGenerateRefreshToken

	funcRefreshTokenTTL          func() (d1 time.Duration)
	funcRefreshTokenTTLOrigin    string
	inspectFuncRefreshTokenTTL   func()
	afterRefreshTokenTTLCounter  uint64
	beforeRefreshTokenTTLCounter uint64
	RefreshTokenTTLMock          mJWTManagerMockRefreshTokenTTL

	funcVerifyAccessToken          func(tokenString string) (cp1 *Claims, err error)
	funcVerifyAccessTokenOrigin    string
	inspectFuncVerifyAccessToken   func(tokenString string)
	afterVerifyAccessTokenCounter  uint64
	beforeVerifyAccessTokenCounter uint64
	VerifyAccessTokenMock          mJWTManagerMockVerifyAccessToken

	funcVerifyRefreshToken          func(tokenString string) (cp1 *Claims, err error)
	funcVerifyRefreshTokenOrigin    string
	inspectFuncVerifyRefreshToken   func(tokenString string)
	afterVerifyRefreshTokenCounter  uint64
	beforeVerifyRefreshTokenCounter uint64
	VerifyRefreshTokenMock          mJWTManagerMockVerifyRefreshToken
}

// NewJWTManagerMock returns a mock for Manager
func NewJWTManagerMock(t minimock.Tester) *JWTManagerMock {
	m := &JWTManagerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AccessTokenTTLMock = mJWTManagerMockAccessTokenTTL{mock: m}

	m.GenerateAccessTokenMock = mJWTManagerMockGenerateAccessToken{mock: m}
	m.GenerateAccessTokenMock.callArgs = []*JWTManagerMockGenerateAccessTokenParams{}

	m.GenerateRefreshTokenMock = mJWTManagerMockGenerateRefreshToken{mock: m}
	m.GenerateRefreshTokenMock.callArgs = []*JWTManagerMockGenerateRefreshTokenParams{}

	m.RefreshTokenTTLMock = mJWTManagerMockRefreshTokenTTL{mock: m}

	m.VerifyAccessTokenMock = mJWTManagerMockVerifyAccessToken{mock: m}
	m.VerifyAccessTokenMock.callArgs = []*JWTManagerMockVerifyAccessTokenParams{}

	m.VerifyRefreshTokenMock = mJWTManagerMockVerifyRefreshToken{mock: m}
	m.VerifyRefreshTokenMock.callArgs = []*JWTManagerMockVerifyRefreshTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mJWTManagerMockAccessTokenTTL struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockAccessTokenTTLExpectation
	expectations       []*JWTManagerMockAccessTokenTTLExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockAccessTokenTTLExpectation specifies expectation struct of the Manager.AccessTokenTTL
type JWTManagerMockAccessTokenTTLExpectation struct {
	mock *JWTManagerMock

	results      *JWTManagerMockAccessTokenTTLResults
	returnOrigin string
	Counter      uint64
}

// JWTManagerMockAccessTokenTTLResults contains results of the Manager.AccessTokenTTL
type JWTManagerMockAccessTokenTTLResults struct {
	d1 time.Duration
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Optional() *mJWTManagerMockAccessTokenTTL {
	mmAccessTokenTTL.optional = true
	return mmAccessTokenTTL
}

// Expect sets up expected params for Manager.AccessTokenTTL
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Expect() *mJWTManagerMockAccessTokenTTL {
	if mmAccessTokenTTL.mock.funcAccessTokenTTL != nil {
		mmAccessTokenTTL.mock.t.Fatalf("JWTManagerMock.AccessTokenTTL mock is already set by Set")
	}

	if mmAccessTokenTTL.defaultExpectation == nil {
		mmAccessTokenTTL.defaultExpectation = &JWTManagerMockAccessTokenTTLExpectation{}
	}

	return mmAccessTokenTTL
}

// Inspect accepts an inspector function that has same arguments as the Manager.AccessTokenTTL
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Inspect(f func()) *mJWTManagerMockAccessTokenTTL {
	if mmAccessTokenTTL.mock.inspectFuncAccessTokenTTL != nil {
		mmAccessTokenTTL.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.AccessTokenTTL")
	}

	mmAccessTokenTTL.mock.inspectFuncAccessTokenTTL = f

	return mmAccessTokenTTL
}

// Return sets up results that will be returned by Manager.AccessTokenTTL
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Return(d1 time.Duration) *JWTManagerMock {
	if mmAccessTokenTTL.mock.funcAccessTokenTTL != nil {
		mmAccessTokenTTL.mock.t.Fatalf("JWTManagerMock.AccessTokenTTL mock is already set by Set")
	}

	if mmAccessTokenTTL.defaultExpectation == nil {
		mmAccessTokenTTL.defaultExpectation = &JWTManagerMockAccessTokenTTLExpectation{mock: mmAccessTokenTTL.mock}
	}
	mmAccessTokenTTL.defaultExpectation.results = &JWTManagerMockAccessTokenTTLResults{d1}
	mmAccessTokenTTL.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAccessTokenTTL.mock
}

// Set uses given function f to mock the Manager.AccessTokenTTL method
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Set(f func() (d1 time.Duration)) *JWTManagerMock {
	if mmAccessTokenTTL.defaultExpectation != nil {
		mmAccessTokenTTL.mock.t.Fatalf("Default expectation is already set for the Manager.AccessTokenTTL method")
	}

	if len(mmAccessTokenTTL.expectations) > 0 {
		mmAccessTokenTTL.mock.t.Fatalf("Some expectations are already set for the Manager.AccessTokenTTL method")
	}

	mmAccessTokenTTL.mock.funcAccessTokenTTL = f
	mmAccessTokenTTL.mock.funcAccessTokenTTLOrigin = minimock.CallerInfo(1)
	return mmAccessTokenTTL.mock
}

// Times sets number of times Manager.AccessTokenTTL should be invoked
func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) Times(n uint64) *mJWTManagerMockAccessTokenTTL {
	if n == 0 {
		mmAccessTokenTTL.mock.t.Fatalf("Times of JWTManagerMock.AccessTokenTTL mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAccessTokenTTL.expectedInvocations, n)
	mmAccessTokenTTL.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAccessTokenTTL
}

func (mmAccessTokenTTL *mJWTManagerMockAccessTokenTTL) invocationsDone() bool {
	if len(mmAccessTokenTTL.expectations) == 0 && mmAccessTokenTTL.defaultExpectation == nil && mmAccessTokenTTL.mock.funcAccessTokenTTL == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAccessTokenTTL.mock.afterAccessTokenTTLCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAccessTokenTTL.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AccessTokenTTL implements Manager
func (mmAccessTokenTTL *JWTManagerMock) AccessTokenTTL() (d1 time.Duration) {
	mm_atomic.AddUint64(&mmAccessTokenTTL.beforeAccessTokenTTLCounter, 1)
	defer mm_atomic.AddUint64(&mmAccessTokenTTL.afterAccessTokenTTLCounter, 1)

	mmAccessTokenTTL.t.Helper()

	if mmAccessTokenTTL.inspectFuncAccessTokenTTL != nil {
		mmAccessTokenTTL.inspectFuncAccessTokenTTL()
	}

	if mmAccessTokenTTL.AccessTokenTTLMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAccessTokenTTL.AccessTokenTTLMock.defaultExpectation.Counter, 1)

		mm_results := mmAccessTokenTTL.AccessTokenTTLMock.defaultExpectation.results
		if mm_results == nil {
			mmAccessTokenTTL.t.Fatal("No results are set for the JWTManagerMock.AccessTokenTTL")
		}
		return (*mm_results).d1
	}
	if mmAccessTokenTTL.funcAccessTokenTTL != nil {
		return mmAccessTokenTTL.funcAccessTokenTTL()
	}
	mmAccessTokenTTL.t.Fatalf("Unexpected call to JWTManagerMock.AccessTokenTTL.")
	return
}

// AccessTokenTTLAfterCounter returns a count of finished JWTManagerMock.AccessTokenTTL invocations
func (mmAccessTokenTTL *JWTManagerMock) AccessTokenTTLAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAccessTokenTTL.afterAccessTokenTTLCounter)
}

// AccessTokenTTLBeforeCounter returns a count of JWTManagerMock.AccessTokenTTL invocations
func (mmAccessTokenTTL *JWTManagerMock) AccessTokenTTLBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAccessTokenTTL.beforeAccessTokenTTLCounter)
}

// MinimockAccessTokenTTLDone returns true if the count of the AccessTokenTTL invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockAccessTokenTTLDone() bool {
	if m.AccessTokenTTLMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AccessTokenTTLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AccessTokenTTLMock.invocationsDone()
}

// MinimockAccessTokenTTLInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockAccessTokenTTLInspect() {
	for _, e := range m.AccessTokenTTLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to JWTManagerMock.AccessTokenTTL")
		}
	}

	afterAccessTokenTTLCounter := mm_atomic.LoadUint64(&m.afterAccessTokenTTLCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AccessTokenTTLMock.defaultExpectation != nil && afterAccessTokenTTLCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.AccessTokenTTL at\n%s", m.AccessTokenTTLMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAccessTokenTTL != nil && afterAccessTokenTTLCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.AccessTokenTTL at\n%s", m.funcAccessTokenTTLOrigin)
	}

	if !m.AccessTokenTTLMock.invocationsDone() && afterAccessTokenTTLCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.AccessTokenTTL at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AccessTokenTTLMock.expectedInvocations), m.AccessTokenTTLMock.expectedInvocationsOrigin, afterAccessTokenTTLCounter)
	}
}

type mJWTManagerMockGenerateAccessToken struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockGenerateAccessTokenExpectation
	expectations       []*JWTManagerMockGenerateAccessTokenExpectation

	callArgs []*JWTManagerMockGenerateAccessTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockGenerateAccessTokenExpectation specifies expectation struct of the Manager.GenerateAccessToken
type JWTManagerMockGenerateAccessTokenExpectation struct {
	mock               *JWTManagerMock
	params             *JWTManagerMockGenerateAccessTokenParams
	paramPtrs          *JWTManagerMockGenerateAccessTokenParamPtrs
	expectationOrigins JWTManagerMockGenerateAccessTokenExpectationOrigins
	results            *JWTManagerMockGenerateAccessTokenResults
	returnOrigin       string
	Counter            uint64
}

// JWTManagerMockGenerateAccessTokenParams contains parameters of the Manager.GenerateAccessToken
type JWTManagerMockGenerateAccessTokenParams struct {
	claims Claims
}

// JWTManagerMockGenerateAccessTokenParamPtrs contains pointers to parameters of the Manager.GenerateAccessToken
type JWTManagerMockGenerateAccessTokenParamPtrs struct {
	claims *Claims
}

// JWTManagerMockGenerateAccessTokenResults contains results of the Manager.GenerateAccessToken
type JWTManagerMockGenerateAccessTokenResults struct {
	s1  string
	err error
}

// JWTManagerMockGenerateAccessTokenOrigins contains origins of expectations of the Manager.GenerateAccessToken
type JWTManagerMockGenerateAccessTokenExpectationOrigins struct {
	origin       string
	originClaims string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Optional() *mJWTManagerMockGenerateAccessToken {
	mmGenerateAccessToken.optional = true
	return mmGenerateAccessToken
}

// Expect sets up expected params for Manager.GenerateAccessToken
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Expect(claims Claims) *mJWTManagerMockGenerateAccessToken {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by Set")
	}

	if mmGenerateAccessToken.defaultExpectation == nil {
		mmGenerateAccessToken.defaultExpectation = &JWTManagerMockGenerateAccessTokenExpectation{}
	}

	if mmGenerateAccessToken.defaultExpectation.paramPtrs != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by ExpectParams functions")
	}

	mmGenerateAccessToken.defaultExpectation.params = &JWTManagerMockGenerateAccessTokenParams{claims}
	mmGenerateAccessToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGenerateAccessToken.expectations {
		if minimock.Equal(e.params, mmGenerateAccessToken.defaultExpectation.params) {
			mmGenerateAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateAccessToken.defaultExpectation.params)
		}
	}

	return mmGenerateAccessToken
}

// ExpectClaimsParam1 sets up expected param claims for Manager.GenerateAccessToken
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) ExpectClaimsParam1(claims Claims) *mJWTManagerMockGenerateAccessToken {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by Set")
	}

	if mmGenerateAccessToken.defaultExpectation == nil {
		mmGenerateAccessToken.defaultExpectation = &JWTManagerMockGenerateAccessTokenExpectation{}
	}

	if mmGenerateAccessToken.defaultExpectation.params != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by Expect")
	}

	if mmGenerateAccessToken.defaultExpectation.paramPtrs == nil {
		mmGenerateAccessToken.defaultExpectation.paramPtrs = &JWTManagerMockGenerateAccessTokenParamPtrs{}
	}
	mmGenerateAccessToken.defaultExpectation.paramPtrs.claims = &claims
	mmGenerateAccessToken.defaultExpectation.expectationOrigins.originClaims = minimock.CallerInfo(1)

	return mmGenerateAccessToken
}

// Inspect accepts an inspector function that has same arguments as the Manager.GenerateAccessToken
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Inspect(f func(claims Claims)) *mJWTManagerMockGenerateAccessToken {
	if mmGenerateAccessToken.mock.inspectFuncGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.GenerateAccessToken")
	}

	mmGenerateAccessToken.mock.inspectFuncGenerateAccessToken = f

	return mmGenerateAccessToken
}

// Return sets up results that will be returned by Manager.GenerateAccessToken
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Return(s1 string, err error) *JWTManagerMock {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by Set")
	}

	if mmGenerateAccessToken.defaultExpectation == nil {
		mmGenerateAccessToken.defaultExpectation = &JWTManagerMockGenerateAccessTokenExpectation{mock: mmGenerateAccessToken.mock}
	}
	mmGenerateAccessToken.defaultExpectation.results = &JWTManagerMockGenerateAccessTokenResults{s1, err}
	mmGenerateAccessToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGenerateAccessToken.mock
}

// Set uses given function f to mock the Manager.GenerateAccessToken method
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Set(f func(claims Claims) (s1 string, err error)) *JWTManagerMock {
	if mmGenerateAccessToken.defaultExpectation != nil {
		mmGenerateAccessToken.mock.t.Fatalf("Default expectation is already set for the Manager.GenerateAccessToken method")
	}

	if len(mmGenerateAccessToken.expectations) > 0 {
		mmGenerateAccessToken.mock.t.Fatalf("Some expectations are already set for the Manager.GenerateAccessToken method")
	}

	mmGenerateAccessToken.mock.funcGenerateAccessToken = f
	mmGenerateAccessToken.mock.funcGenerateAccessTokenOrigin = minimock.CallerInfo(1)
	return mmGenerateAccessToken.mock
}

// When sets expectation for the Manager.GenerateAccessToken which will trigger the result defined by the following
// Then helper
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) When(claims Claims) *JWTManagerMockGenerateAccessTokenExpectation {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("JWTManagerMock.GenerateAccessToken mock is already set by Set")
	}

	expectation := &JWTManagerMockGenerateAccessTokenExpectation{
		mock:               mmGenerateAccessToken.mock,
		params:             &JWTManagerMockGenerateAccessTokenParams{claims},
		expectationOrigins: JWTManagerMockGenerateAccessTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGenerateAccessToken.expectations = append(mmGenerateAccessToken.expectations, expectation)
	return expectation
}

// Then sets up Manager.GenerateAccessToken return parameters for the expectation previously defined by the When method
func (e *JWTManagerMockGenerateAccessTokenExpectation) Then(s1 string, err error) *JWTManagerMock {
	e.results = &JWTManagerMockGenerateAccessTokenResults{s1, err}
	return e.mock
}

// Times sets number of times Manager.GenerateAccessToken should be invoked
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Times(n uint64) *mJWTManagerMockGenerateAccessToken {
	if n == 0 {
		mmGenerateAccessToken.mock.t.Fatalf("Times of JWTManagerMock.GenerateAccessToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateAccessToken.expectedInvocations, n)
	mmGenerateAccessToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGenerateAccessToken
}

func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) invocationsDone() bool {
	if len(mmGenerateAccessToken.expectations) == 0 && mmGenerateAccessToken.defaultExpectation == nil && mmGenerateAccessToken.mock.funcGenerateAccessToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateAccessToken.mock.afterGenerateAccessTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateAccessToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateAccessToken implements Manager
func (mmGenerateAccessToken *JWTManagerMock) GenerateAccessToken(claims Claims) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateAccessToken.beforeGenerateAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateAccessToken.afterGenerateAccessTokenCounter, 1)

	mmGenerateAccessToken.t.Helper()

	if mmGenerateAccessToken.inspectFuncGenerateAccessToken != nil {
		mmGenerateAccessToken.inspectFuncGenerateAccessToken(claims)
	}

	mm_params := JWTManagerMockGenerateAccessTokenParams{claims}

	// Record call args
	mmGenerateAccessToken.GenerateAccessTokenMock.mutex.Lock()
	mmGenerateAccessToken.GenerateAccessTokenMock.callArgs = append(mmGenerateAccessToken.GenerateAccessTokenMock.callArgs, &mm_params)
	mmGenerateAccessToken.GenerateAccessTokenMock.mutex.Unlock()

	for _, e := range mmGenerateAccessToken.GenerateAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.paramPtrs

		mm_got := JWTManagerMockGenerateAccessTokenParams{claims}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.claims != nil && !minimock.Equal(*mm_want_ptrs.claims, mm_got.claims) {
				mmGenerateAccessToken.t.Errorf("JWTManagerMock.GenerateAccessToken got unexpected parameter claims, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.expectationOrigins.originClaims, *mm_want_ptrs.claims, mm_got.claims, minimock.Diff(*mm_want_ptrs.claims, mm_got.claims))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateAccessToken.t.Errorf("JWTManagerMock.GenerateAccessToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateAccessToken.t.Fatal("No results are set for the JWTManagerMock.GenerateAccessToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateAccessToken.funcGenerateAccessToken != nil {
		return mmGenerateAccessToken.funcGenerateAccessToken(claims)
	}
	mmGenerateAccessToken.t.Fatalf("Unexpected call to JWTManagerMock.GenerateAccessToken. %v", claims)
	return
}

// GenerateAccessTokenAfterCounter returns a count of finished JWTManagerMock.GenerateAccessToken invocations
func (mmGenerateAccessToken *JWTManagerMock) GenerateAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateAccessToken.afterGenerateAccessTokenCounter)
}

// GenerateAccessTokenBeforeCounter returns a count of JWTManagerMock.GenerateAccessToken invocations
func (mmGenerateAccessToken *JWTManagerMock) GenerateAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateAccessToken.beforeGenerateAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to JWTManagerMock.GenerateAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateAccessToken *mJWTManagerMockGenerateAccessToken) Calls() []*JWTManagerMockGenerateAccessTokenParams {
	mmGenerateAccessToken.mutex.RLock()

	argCopy := make([]*JWTManagerMockGenerateAccessTokenParams, len(mmGenerateAccessToken.callArgs))
	copy(argCopy, mmGenerateAccessToken.callArgs)

	mmGenerateAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateAccessTokenDone returns true if the count of the GenerateAccessToken invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockGenerateAccessTokenDone() bool {
	if m.GenerateAccessTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateAccessTokenMock.invocationsDone()
}

// MinimockGenerateAccessTokenInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockGenerateAccessTokenInspect() {
	for _, e := range m.GenerateAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateAccessToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGenerateAccessTokenCounter := mm_atomic.LoadUint64(&m.afterGenerateAccessTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateAccessTokenMock.defaultExpectation != nil && afterGenerateAccessTokenCounter < 1 {
		if m.GenerateAccessTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateAccessToken at\n%s", m.GenerateAccessTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateAccessToken at\n%s with params: %#v", m.GenerateAccessTokenMock.defaultExpectation.expectationOrigins.origin, *m.GenerateAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateAccessToken != nil && afterGenerateAccessTokenCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.GenerateAccessToken at\n%s", m.funcGenerateAccessTokenOrigin)
	}

	if !m.GenerateAccessTokenMock.invocationsDone() && afterGenerateAccessTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.GenerateAccessToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateAccessTokenMock.expectedInvocations), m.GenerateAccessTokenMock.expectedInvocationsOrigin, afterGenerateAccessTokenCounter)
	}
}

type mJWTManagerMockGenerateRefreshToken struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockGenerateRefreshTokenExpectation
	expectations       []*JWTManagerMockGenerateRefreshTokenExpectation

	callArgs []*JWTManagerMockGenerateRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockGenerateRefreshTokenExpectation specifies expectation struct of the Manager.GenerateRefreshToken
type JWTManagerMockGenerateRefreshTokenExpectation struct {
	mock               *JWTManagerMock
	params             *JWTManagerMockGenerateRefreshTokenParams
	paramPtrs          *JWTManagerMockGenerateRefreshTokenParamPtrs
	expectationOrigins JWTManagerMockGenerateRefreshTokenExpectationOrigins
	results            *JWTManagerMockGenerateRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// JWTManagerMockGenerateRefreshTokenParams contains parameters of the Manager.GenerateRefreshToken
type JWTManagerMockGenerateRefreshTokenParams struct {
	claims Claims
}

// JWTManagerMockGenerateRefreshTokenParamPtrs contains pointers to parameters of the Manager.GenerateRefreshToken
type JWTManagerMockGenerateRefreshTokenParamPtrs struct {
	claims *Claims
}

// JWTManagerMockGenerateRefreshTokenResults contains results of the Manager.GenerateRefreshToken
type JWTManagerMockGenerateRefreshTokenResults struct {
	s1  string
	err error
}

// JWTManagerMockGenerateRefreshTokenOrigins contains origins of expectations of the Manager.GenerateRefreshToken
type JWTManagerMockGenerateRefreshTokenExpectationOrigins struct {
	origin       string
	originClaims string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Optional() *mJWTManagerMockGenerateRefreshToken {
	mmGenerateRefreshToken.optional = true
	return mmGenerateRefreshToken
}

// Expect sets up expected params for Manager.GenerateRefreshToken
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Expect(claims Claims) *mJWTManagerMockGenerateRefreshToken {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by Set")
	}

	if mmGenerateRefreshToken.defaultExpectation == nil {
		mmGenerateRefreshToken.defaultExpectation = &JWTManagerMockGenerateRefreshTokenExpectation{}
	}

	if mmGenerateRefreshToken.defaultExpectation.paramPtrs != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by ExpectParams functions")
	}

	mmGenerateRefreshToken.defaultExpectation.params = &JWTManagerMockGenerateRefreshTokenParams{claims}
	mmGenerateRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGenerateRefreshToken.expectations {
		if minimock.Equal(e.params, mmGenerateRefreshToken.defaultExpectation.params) {
			mmGenerateRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateRefreshToken.defaultExpectation.params)
		}
	}

	return mmGenerateRefreshToken
}

// ExpectClaimsParam1 sets up expected param claims for Manager.GenerateRefreshToken
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) ExpectClaimsParam1(claims Claims) *mJWTManagerMockGenerateRefreshToken {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by Set")
	}

	if mmGenerateRefreshToken.defaultExpectation == nil {
		mmGenerateRefreshToken.defaultExpectation = &JWTManagerMockGenerateRefreshTokenExpectation{}
	}

	if mmGenerateRefreshToken.defaultExpectation.params != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by Expect")
	}

	if mmGenerateRefreshToken.defaultExpectation.paramPtrs == nil {
		mmGenerateRefreshToken.defaultExpectation.paramPtrs = &JWTManagerMockGenerateRefreshTokenParamPtrs{}
	}
	mmGenerateRefreshToken.defaultExpectation.paramPtrs.claims = &claims
	mmGenerateRefreshToken.defaultExpectation.expectationOrigins.originClaims = minimock.CallerInfo(1)

	return mmGenerateRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the Manager.GenerateRefreshToken
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Inspect(f func(claims Claims)) *mJWTManagerMockGenerateRefreshToken {
	if mmGenerateRefreshToken.mock.inspectFuncGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.GenerateRefreshToken")
	}

	mmGenerateRefreshToken.mock.inspectFuncGenerateRefreshToken = f

	return mmGenerateRefreshToken
}

// Return sets up results that will be returned by Manager.GenerateRefreshToken
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Return(s1 string, err error) *JWTManagerMock {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by Set")
	}

	if mmGenerateRefreshToken.defaultExpectation == nil {
		mmGenerateRefreshToken.defaultExpectation = &JWTManagerMockGenerateRefreshTokenExpectation{mock: mmGenerateRefreshToken.mock}
	}
	mmGenerateRefreshToken.defaultExpectation.results = &JWTManagerMockGenerateRefreshTokenResults{s1, err}
	mmGenerateRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGenerateRefreshToken.mock
}

// Set uses given function f to mock the Manager.GenerateRefreshToken method
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Set(f func(claims Claims) (s1 string, err error)) *JWTManagerMock {
	if mmGenerateRefreshToken.defaultExpectation != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("Default expectation is already set for the Manager.GenerateRefreshToken method")
	}

	if len(mmGenerateRefreshToken.expectations) > 0 {
		mmGenerateRefreshToken.mock.t.Fatalf("Some expectations are already set for the Manager.GenerateRefreshToken method")
	}

	mmGenerateRefreshToken.mock.funcGenerateRefreshToken = f
	mmGenerateRefreshToken.mock.funcGenerateRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmGenerateRefreshToken.mock
}

// When sets expectation for the Manager.GenerateRefreshToken which will trigger the result defined by the following
// Then helper
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) When(claims Claims) *JWTManagerMockGenerateRefreshTokenExpectation {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("JWTManagerMock.GenerateRefreshToken mock is already set by Set")
	}

	expectation := &JWTManagerMockGenerateRefreshTokenExpectation{
		mock:               mmGenerateRefreshToken.mock,
		params:             &JWTManagerMockGenerateRefreshTokenParams{claims},
		expectationOrigins: JWTManagerMockGenerateRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGenerateRefreshToken.expectations = append(mmGenerateRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up Manager.GenerateRefreshToken return parameters for the expectation previously defined by the When method
func (e *JWTManagerMockGenerateRefreshTokenExpectation) Then(s1 string, err error) *JWTManagerMock {
	e.results = &JWTManagerMockGenerateRefreshTokenResults{s1, err}
	return e.mock
}

// Times sets number of times Manager.GenerateRefreshToken should be invoked
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Times(n uint64) *mJWTManagerMockGenerateRefreshToken {
	if n == 0 {
		mmGenerateRefreshToken.mock.t.Fatalf("Times of JWTManagerMock.GenerateRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateRefreshToken.expectedInvocations, n)
	mmGenerateRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGenerateRefreshToken
}

func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) invocationsDone() bool {
	if len(mmGenerateRefreshToken.expectations) == 0 && mmGenerateRefreshToken.defaultExpectation == nil && mmGenerateRefreshToken.mock.funcGenerateRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateRefreshToken.mock.afterGenerateRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateRefreshToken implements Manager
func (mmGenerateRefreshToken *JWTManagerMock) GenerateRefreshToken(claims Claims) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateRefreshToken.beforeGenerateRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateRefreshToken.afterGenerateRefreshTokenCounter, 1)

	mmGenerateRefreshToken.t.Helper()

	if mmGenerateRefreshToken.inspectFuncGenerateRefreshToken != nil {
		mmGenerateRefreshToken.inspectFuncGenerateRefreshToken(claims)
	}

	mm_params := JWTManagerMockGenerateRefreshTokenParams{claims}

	// Record call args
	mmGenerateRefreshToken.GenerateRefreshTokenMock.mutex.Lock()
	mmGenerateRefreshToken.GenerateRefreshTokenMock.callArgs = append(mmGenerateRefreshToken.GenerateRefreshTokenMock.callArgs, &mm_params)
	mmGenerateRefreshToken.GenerateRefreshTokenMock.mutex.Unlock()

	for _, e := range mmGenerateRefreshToken.GenerateRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := JWTManagerMockGenerateRefreshTokenParams{claims}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.claims != nil && !minimock.Equal(*mm_want_ptrs.claims, mm_got.claims) {
				mmGenerateRefreshToken.t.Errorf("JWTManagerMock.GenerateRefreshToken got unexpected parameter claims, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.expectationOrigins.originClaims, *mm_want_ptrs.claims, mm_got.claims, minimock.Diff(*mm_want_ptrs.claims, mm_got.claims))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateRefreshToken.t.Errorf("JWTManagerMock.GenerateRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateRefreshToken.t.Fatal("No results are set for the JWTManagerMock.GenerateRefreshToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateRefreshToken.funcGenerateRefreshToken != nil {
		return mmGenerateRefreshToken.funcGenerateRefreshToken(claims)
	}
	mmGenerateRefreshToken.t.Fatalf("Unexpected call to JWTManagerMock.GenerateRefreshToken. %v", claims)
	return
}

// GenerateRefreshTokenAfterCounter returns a count of finished JWTManagerMock.GenerateRefreshToken invocations
func (mmGenerateRefreshToken *JWTManagerMock) GenerateRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateRefreshToken.afterGenerateRefreshTokenCounter)
}

// GenerateRefreshTokenBeforeCounter returns a count of JWTManagerMock.GenerateRefreshToken invocations
func (mmGenerateRefreshToken *JWTManagerMock) GenerateRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateRefreshToken.beforeGenerateRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to JWTManagerMock.GenerateRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateRefreshToken *mJWTManagerMockGenerateRefreshToken) Calls() []*JWTManagerMockGenerateRefreshTokenParams {
	mmGenerateRefreshToken.mutex.RLock()

	argCopy := make([]*JWTManagerMockGenerateRefreshTokenParams, len(mmGenerateRefreshToken.callArgs))
	copy(argCopy, mmGenerateRefreshToken.callArgs)

	mmGenerateRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateRefreshTokenDone returns true if the count of the GenerateRefreshToken invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockGenerateRefreshTokenDone() bool {
	if m.GenerateRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateRefreshTokenMock.invocationsDone()
}

// MinimockGenerateRefreshTokenInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockGenerateRefreshTokenInspect() {
	for _, e := range m.GenerateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGenerateRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterGenerateRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateRefreshTokenMock.defaultExpectation != nil && afterGenerateRefreshTokenCounter < 1 {
		if m.GenerateRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateRefreshToken at\n%s", m.GenerateRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to JWTManagerMock.GenerateRefreshToken at\n%s with params: %#v", m.GenerateRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.GenerateRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateRefreshToken != nil && afterGenerateRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.GenerateRefreshToken at\n%s", m.funcGenerateRefreshTokenOrigin)
	}

	if !m.GenerateRefreshTokenMock.invocationsDone() && afterGenerateRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.GenerateRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateRefreshTokenMock.expectedInvocations), m.GenerateRefreshTokenMock.expectedInvocationsOrigin, afterGenerateRefreshTokenCounter)
	}
}

type mJWTManagerMockRefreshTokenTTL struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockRefreshTokenTTLExpectation
	expectations       []*JWTManagerMockRefreshTokenTTLExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockRefreshTokenTTLExpectation specifies expectation struct of the Manager.RefreshTokenTTL
type JWTManagerMockRefreshTokenTTLExpectation struct {
	mock *JWTManagerMock

	results      *JWTManagerMockRefreshTokenTTLResults
	returnOrigin string
	Counter      uint64
}

// JWTManagerMockRefreshTokenTTLResults contains results of the Manager.RefreshTokenTTL
type JWTManagerMockRefreshTokenTTLResults struct {
	d1 time.Duration
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Optional() *mJWTManagerMockRefreshTokenTTL {
	mmRefreshTokenTTL.optional = true
	return mmRefreshTokenTTL
}

// Expect sets up expected params for Manager.RefreshTokenTTL
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Expect() *mJWTManagerMockRefreshTokenTTL {
	if mmRefreshTokenTTL.mock.funcRefreshTokenTTL != nil {
		mmRefreshTokenTTL.mock.t.Fatalf("JWTManagerMock.RefreshTokenTTL mock is already set by Set")
	}

	if mmRefreshTokenTTL.defaultExpectation == nil {
		mmRefreshTokenTTL.defaultExpectation = &JWTManagerMockRefreshTokenTTLExpectation{}
	}

	return mmRefreshTokenTTL
}

// Inspect accepts an inspector function that has same arguments as the Manager.RefreshTokenTTL
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Inspect(f func()) *mJWTManagerMockRefreshTokenTTL {
	if mmRefreshTokenTTL.mock.inspectFuncRefreshTokenTTL != nil {
		mmRefreshTokenTTL.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.RefreshTokenTTL")
	}

	mmRefreshTokenTTL.mock.inspectFuncRefreshTokenTTL = f

	return mmRefreshTokenTTL
}

// Return sets up results that will be returned by Manager.RefreshTokenTTL
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Return(d1 time.Duration) *JWTManagerMock {
	if mmRefreshTokenTTL.mock.funcRefreshTokenTTL != nil {
		mmRefreshTokenTTL.mock.t.Fatalf("JWTManagerMock.RefreshTokenTTL mock is already set by Set")
	}

	if mmRefreshTokenTTL.defaultExpectation == nil {
		mmRefreshTokenTTL.defaultExpectation = &JWTManagerMockRefreshTokenTTLExpectation{mock: mmRefreshTokenTTL.mock}
	}
	mmRefreshTokenTTL.defaultExpectation.results = &JWTManagerMockRefreshTokenTTLResults{d1}
	mmRefreshTokenTTL.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRefreshTokenTTL.mock
}

// Set uses given function f to mock the Manager.RefreshTokenTTL method
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Set(f func() (d1 time.Duration)) *JWTManagerMock {
	if mmRefreshTokenTTL.defaultExpectation != nil {
		mmRefreshTokenTTL.mock.t.Fatalf("Default expectation is already set for the Manager.RefreshTokenTTL method")
	}

	if len(mmRefreshTokenTTL.expectations) > 0 {
		mmRefreshTokenTTL.mock.t.Fatalf("Some expectations are already set for the Manager.RefreshTokenTTL method")
	}

	mmRefreshTokenTTL.mock.funcRefreshTokenTTL = f
	mmRefreshTokenTTL.mock.funcRefreshTokenTTLOrigin = minimock.CallerInfo(1)
	return mmRefreshTokenTTL.mock
}

// Times sets number of times Manager.RefreshTokenTTL should be invoked
func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) Times(n uint64) *mJWTManagerMockRefreshTokenTTL {
	if n == 0 {
		mmRefreshTokenTTL.mock.t.Fatalf("Times of JWTManagerMock.RefreshTokenTTL mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRefreshTokenTTL.expectedInvocations, n)
	mmRefreshTokenTTL.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRefreshTokenTTL
}

func (mmRefreshTokenTTL *mJWTManagerMockRefreshTokenTTL) invocationsDone() bool {
	if len(mmRefreshTokenTTL.expectations) == 0 && mmRefreshTokenTTL.defaultExpectation == nil && mmRefreshTokenTTL.mock.funcRefreshTokenTTL == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRefreshTokenTTL.mock.afterRefreshTokenTTLCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRefreshTokenTTL.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RefreshTokenTTL implements Manager
func (mmRefreshTokenTTL *JWTManagerMock) RefreshTokenTTL() (d1 time.Duration) {
	mm_atomic.AddUint64(&mmRefreshTokenTTL.beforeRefreshTokenTTLCounter, 1)
	defer mm_atomic.AddUint64(&mmRefreshTokenTTL.afterRefreshTokenTTLCounter, 1)

	mmRefreshTokenTTL.t.Helper()

	if mmRefreshTokenTTL.inspectFuncRefreshTokenTTL != nil {
		mmRefreshTokenTTL.inspectFuncRefreshTokenTTL()
	}

	if mmRefreshTokenTTL.RefreshTokenTTLMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRefreshTokenTTL.RefreshTokenTTLMock.defaultExpectation.Counter, 1)

		mm_results := mmRefreshTokenTTL.RefreshTokenTTLMock.defaultExpectation.results
		if mm_results == nil {
			mmRefreshTokenTTL.t.Fatal("No results are set for the JWTManagerMock.RefreshTokenTTL")
		}
		return (*mm_results).d1
	}
	if mmRefreshTokenTTL.funcRefreshTokenTTL != nil {
		return mmRefreshTokenTTL.funcRefreshTokenTTL()
	}
	mmRefreshTokenTTL.t.Fatalf("Unexpected call to JWTManagerMock.RefreshTokenTTL.")
	return
}

// RefreshTokenTTLAfterCounter returns a count of finished JWTManagerMock.RefreshTokenTTL invocations
func (mmRefreshTokenTTL *JWTManagerMock) RefreshTokenTTLAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefreshTokenTTL.afterRefreshTokenTTLCounter)
}

// RefreshTokenTTLBeforeCounter returns a count of JWTManagerMock.RefreshTokenTTL invocations
func (mmRefreshTokenTTL *JWTManagerMock) RefreshTokenTTLBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefreshTokenTTL.beforeRefreshTokenTTLCounter)
}

// MinimockRefreshTokenTTLDone returns true if the count of the RefreshTokenTTL invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockRefreshTokenTTLDone() bool {
	if m.RefreshTokenTTLMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RefreshTokenTTLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RefreshTokenTTLMock.invocationsDone()
}

// MinimockRefreshTokenTTLInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockRefreshTokenTTLInspect() {
	for _, e := range m.RefreshTokenTTLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to JWTManagerMock.RefreshTokenTTL")
		}
	}

	afterRefreshTokenTTLCounter := mm_atomic.LoadUint64(&m.afterRefreshTokenTTLCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RefreshTokenTTLMock.defaultExpectation != nil && afterRefreshTokenTTLCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.RefreshTokenTTL at\n%s", m.RefreshTokenTTLMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRefreshTokenTTL != nil && afterRefreshTokenTTLCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.RefreshTokenTTL at\n%s", m.funcRefreshTokenTTLOrigin)
	}

	if !m.RefreshTokenTTLMock.invocationsDone() && afterRefreshTokenTTLCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.RefreshTokenTTL at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RefreshTokenTTLMock.expectedInvocations), m.RefreshTokenTTLMock.expectedInvocationsOrigin, afterRefreshTokenTTLCounter)
	}
}

type mJWTManagerMockVerifyAccessToken struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockVerifyAccessTokenExpectation
	expectations       []*JWTManagerMockVerifyAccessTokenExpectation

	callArgs []*JWTManagerMockVerifyAccessTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockVerifyAccessTokenExpectation specifies expectation struct of the Manager.VerifyAccessToken
type JWTManagerMockVerifyAccessTokenExpectation struct {
	mock               *JWTManagerMock
	params             *JWTManagerMockVerifyAccessTokenParams
	paramPtrs          *JWTManagerMockVerifyAccessTokenParamPtrs
	expectationOrigins JWTManagerMockVerifyAccessTokenExpectationOrigins
	results            *JWTManagerMockVerifyAccessTokenResults
	returnOrigin       string
	Counter            uint64
}

// JWTManagerMockVerifyAccessTokenParams contains parameters of the Manager.VerifyAccessToken
type JWTManagerMockVerifyAccessTokenParams struct {
	tokenString string
}

// JWTManagerMockVerifyAccessTokenParamPtrs contains pointers to parameters of the Manager.VerifyAccessToken
type JWTManagerMockVerifyAccessTokenParamPtrs struct {
	tokenString *string
}

// JWTManagerMockVerifyAccessTokenResults contains results of the Manager.VerifyAccessToken
type JWTManagerMockVerifyAccessTokenResults struct {
	cp1 *Claims
	err error
}

// JWTManagerMockVerifyAccessTokenOrigins contains origins of expectations of the Manager.VerifyAccessToken
type JWTManagerMockVerifyAccessTokenExpectationOrigins struct {
	origin            string
	originTokenString string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Optional() *mJWTManagerMockVerifyAccessToken {
	mmVerifyAccessToken.optional = true
	return mmVerifyAccessToken
}

// Expect sets up expected params for Manager.VerifyAccessToken
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Expect(tokenString string) *mJWTManagerMockVerifyAccessToken {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by Set")
	}

	if mmVerifyAccessToken.defaultExpectation == nil {
		mmVerifyAccessToken.defaultExpectation = &JWTManagerMockVerifyAccessTokenExpectation{}
	}

	if mmVerifyAccessToken.defaultExpectation.paramPtrs != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by ExpectParams functions")
	}

	mmVerifyAccessToken.defaultExpectation.params = &JWTManagerMockVerifyAccessTokenParams{tokenString}
	mmVerifyAccessToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmVerifyAccessToken.expectations {
		if minimock.Equal(e.params, mmVerifyAccessToken.defaultExpectation.params) {
			mmVerifyAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmVerifyAccessToken.defaultExpectation.params)
		}
	}

	return mmVerifyAccessToken
}

// ExpectTokenStringParam1 sets up expected param tokenString for Manager.VerifyAccessToken
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) ExpectTokenStringParam1(tokenString string) *mJWTManagerMockVerifyAccessToken {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by Set")
	}

	if mmVerifyAccessToken.defaultExpectation == nil {
		mmVerifyAccessToken.defaultExpectation = &JWTManagerMockVerifyAccessTokenExpectation{}
	}

	if mmVerifyAccessToken.defaultExpectation.params != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by Expect")
	}

	if mmVerifyAccessToken.defaultExpectation.paramPtrs == nil {
		mmVerifyAccessToken.defaultExpectation.paramPtrs = &JWTManagerMockVerifyAccessTokenParamPtrs{}
	}
	mmVerifyAccessToken.defaultExpectation.paramPtrs.tokenString = &tokenString
	mmVerifyAccessToken.defaultExpectation.expectationOrigins.originTokenString = minimock.CallerInfo(1)

	return mmVerifyAccessToken
}

// Inspect accepts an inspector function that has same arguments as the Manager.VerifyAccessToken
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Inspect(f func(tokenString string)) *mJWTManagerMockVerifyAccessToken {
	if mmVerifyAccessToken.mock.inspectFuncVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.VerifyAccessToken")
	}

	mmVerifyAccessToken.mock.inspectFuncVerifyAccessToken = f

	return mmVerifyAccessToken
}

// Return sets up results that will be returned by Manager.VerifyAccessToken
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Return(cp1 *Claims, err error) *JWTManagerMock {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by Set")
	}

	if mmVerifyAccessToken.defaultExpectation == nil {
		mmVerifyAccessToken.defaultExpectation = &JWTManagerMockVerifyAccessTokenExpectation{mock: mmVerifyAccessToken.mock}
	}
	mmVerifyAccessToken.defaultExpectation.results = &JWTManagerMockVerifyAccessTokenResults{cp1, err}
	mmVerifyAccessToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmVerifyAccessToken.mock
}

// Set uses given function f to mock the Manager.VerifyAccessToken method
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Set(f func(tokenString string) (cp1 *Claims, err error)) *JWTManagerMock {
	if mmVerifyAccessToken.defaultExpectation != nil {
		mmVerifyAccessToken.mock.t.Fatalf("Default expectation is already set for the Manager.VerifyAccessToken method")
	}

	if len(mmVerifyAccessToken.expectations) > 0 {
		mmVerifyAccessToken.mock.t.Fatalf("Some expectations are already set for the Manager.VerifyAccessToken method")
	}

	mmVerifyAccessToken.mock.funcVerifyAccessToken = f
	mmVerifyAccessToken.mock.funcVerifyAccessTokenOrigin = minimock.CallerInfo(1)
	return mmVerifyAccessToken.mock
}

// When sets expectation for the Manager.VerifyAccessToken which will trigger the result defined by the following
// Then helper
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) When(tokenString string) *JWTManagerMockVerifyAccessTokenExpectation {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("JWTManagerMock.VerifyAccessToken mock is already set by Set")
	}

	expectation := &JWTManagerMockVerifyAccessTokenExpectation{
		mock:               mmVerifyAccessToken.mock,
		params:             &JWTManagerMockVerifyAccessTokenParams{tokenString},
		expectationOrigins: JWTManagerMockVerifyAccessTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmVerifyAccessToken.expectations = append(mmVerifyAccessToken.expectations, expectation)
	return expectation
}

// Then sets up Manager.VerifyAccessToken return parameters for the expectation previously defined by the When method
func (e *JWTManagerMockVerifyAccessTokenExpectation) Then(cp1 *Claims, err error) *JWTManagerMock {
	e.results = &JWTManagerMockVerifyAccessTokenResults{cp1, err}
	return e.mock
}

// Times sets number of times Manager.VerifyAccessToken should be invoked
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Times(n uint64) *mJWTManagerMockVerifyAccessToken {
	if n == 0 {
		mmVerifyAccessToken.mock.t.Fatalf("Times of JWTManagerMock.VerifyAccessToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmVerifyAccessToken.expectedInvocations, n)
	mmVerifyAccessToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmVerifyAccessToken
}

func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) invocationsDone() bool {
	if len(mmVerifyAccessToken.expectations) == 0 && mmVerifyAccessToken.defaultExpectation == nil && mmVerifyAccessToken.mock.funcVerifyAccessToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmVerifyAccessToken.mock.afterVerifyAccessTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmVerifyAccessToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// VerifyAccessToken implements Manager
func (mmVerifyAccessToken *JWTManagerMock) VerifyAccessToken(tokenString string) (cp1 *Claims, err error) {
	mm_atomic.AddUint64(&mmVerifyAccessToken.beforeVerifyAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmVerifyAccessToken.afterVerifyAccessTokenCounter, 1)

	mmVerifyAccessToken.t.Helper()

	if mmVerifyAccessToken.inspectFuncVerifyAccessToken != nil {
		mmVerifyAccessToken.inspectFuncVerifyAccessToken(tokenString)
	}

	mm_params := JWTManagerMockVerifyAccessTokenParams{tokenString}

	// Record call args
	mmVerifyAccessToken.VerifyAccessTokenMock.mutex.Lock()
	mmVerifyAccessToken.VerifyAccessTokenMock.callArgs = append(mmVerifyAccessToken.VerifyAccessTokenMock.callArgs, &mm_params)
	mmVerifyAccessToken.VerifyAccessTokenMock.mutex.Unlock()

	for _, e := range mmVerifyAccessToken.VerifyAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.params
		mm_want_ptrs := mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.paramPtrs

		mm_got := JWTManagerMockVerifyAccessTokenParams{tokenString}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.tokenString != nil && !minimock.Equal(*mm_want_ptrs.tokenString, mm_got.tokenString) {
				mmVerifyAccessToken.t.Errorf("JWTManagerMock.VerifyAccessToken got unexpected parameter tokenString, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.expectationOrigins.originTokenString, *mm_want_ptrs.tokenString, mm_got.tokenString, minimock.Diff(*mm_want_ptrs.tokenString, mm_got.tokenString))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmVerifyAccessToken.t.Errorf("JWTManagerMock.VerifyAccessToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmVerifyAccessToken.t.Fatal("No results are set for the JWTManagerMock.VerifyAccessToken")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmVerifyAccessToken.funcVerifyAccessToken != nil {
		return mmVerifyAccessToken.funcVerifyAccessToken(tokenString)
	}
	mmVerifyAccessToken.t.Fatalf("Unexpected call to JWTManagerMock.VerifyAccessToken. %v", tokenString)
	return
}

// VerifyAccessTokenAfterCounter returns a count of finished JWTManagerMock.VerifyAccessToken invocations
func (mmVerifyAccessToken *JWTManagerMock) VerifyAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyAccessToken.afterVerifyAccessTokenCounter)
}

// VerifyAccessTokenBeforeCounter returns a count of JWTManagerMock.VerifyAccessToken invocations
func (mmVerifyAccessToken *JWTManagerMock) VerifyAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyAccessToken.beforeVerifyAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to JWTManagerMock.VerifyAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmVerifyAccessToken *mJWTManagerMockVerifyAccessToken) Calls() []*JWTManagerMockVerifyAccessTokenParams {
	mmVerifyAccessToken.mutex.RLock()

	argCopy := make([]*JWTManagerMockVerifyAccessTokenParams, len(mmVerifyAccessToken.callArgs))
	copy(argCopy, mmVerifyAccessToken.callArgs)

	mmVerifyAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockVerifyAccessTokenDone returns true if the count of the VerifyAccessToken invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockVerifyAccessTokenDone() bool {
	if m.VerifyAccessTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.VerifyAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.VerifyAccessTokenMock.invocationsDone()
}

// MinimockVerifyAccessTokenInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockVerifyAccessTokenInspect() {
	for _, e := range m.VerifyAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyAccessToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterVerifyAccessTokenCounter := mm_atomic.LoadUint64(&m.afterVerifyAccessTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyAccessTokenMock.defaultExpectation != nil && afterVerifyAccessTokenCounter < 1 {
		if m.VerifyAccessTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyAccessToken at\n%s", m.VerifyAccessTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyAccessToken at\n%s with params: %#v", m.VerifyAccessTokenMock.defaultExpectation.expectationOrigins.origin, *m.VerifyAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyAccessToken != nil && afterVerifyAccessTokenCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.VerifyAccessToken at\n%s", m.funcVerifyAccessTokenOrigin)
	}

	if !m.VerifyAccessTokenMock.invocationsDone() && afterVerifyAccessTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.VerifyAccessToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.VerifyAccessTokenMock.expectedInvocations), m.VerifyAccessTokenMock.expectedInvocationsOrigin, afterVerifyAccessTokenCounter)
	}
}

type mJWTManagerMockVerifyRefreshToken struct {
	optional           bool
	mock               *JWTManagerMock
	defaultExpectation *JWTManagerMockVerifyRefreshTokenExpectation
	expectations       []*JWTManagerMockVerifyRefreshTokenExpectation

	callArgs []*JWTManagerMockVerifyRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// JWTManagerMockVerifyRefreshTokenExpectation specifies expectation struct of the Manager.VerifyRefreshToken
type JWTManagerMockVerifyRefreshTokenExpectation struct {
	mock               *JWTManagerMock
	params             *JWTManagerMockVerifyRefreshTokenParams
	paramPtrs          *JWTManagerMockVerifyRefreshTokenParamPtrs
	expectationOrigins JWTManagerMockVerifyRefreshTokenExpectationOrigins
	results            *JWTManagerMockVerifyRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// JWTManagerMockVerifyRefreshTokenParams contains parameters of the Manager.VerifyRefreshToken
type JWTManagerMockVerifyRefreshTokenParams struct {
	tokenString string
}

// JWTManagerMockVerifyRefreshTokenParamPtrs contains pointers to parameters of the Manager.VerifyRefreshToken
type JWTManagerMockVerifyRefreshTokenParamPtrs struct {
	tokenString *string
}

// JWTManagerMockVerifyRefreshTokenResults contains results of the Manager.VerifyRefreshToken
type JWTManagerMockVerifyRefreshTokenResults struct {
	cp1 *Claims
	err error
}

// JWTManagerMockVerifyRefreshTokenOrigins contains origins of expectations of the Manager.VerifyRefreshToken
type JWTManagerMockVerifyRefreshTokenExpectationOrigins struct {
	origin            string
	originTokenString string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Optional() *mJWTManagerMockVerifyRefreshToken {
	mmVerifyRefreshToken.optional = true
	return mmVerifyRefreshToken
}

// Expect sets up expected params for Manager.VerifyRefreshToken
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Expect(tokenString string) *mJWTManagerMockVerifyRefreshToken {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by Set")
	}

	if mmVerifyRefreshToken.defaultExpectation == nil {
		mmVerifyRefreshToken.defaultExpectation = &JWTManagerMockVerifyRefreshTokenExpectation{}
	}

	if mmVerifyRefreshToken.defaultExpectation.paramPtrs != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by ExpectParams functions")
	}

	mmVerifyRefreshToken.defaultExpectation.params = &JWTManagerMockVerifyRefreshTokenParams{tokenString}
	mmVerifyRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmVerifyRefreshToken.expectations {
		if minimock.Equal(e.params, mmVerifyRefreshToken.defaultExpectation.params) {
			mmVerifyRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmVerifyRefreshToken.defaultExpectation.params)
		}
	}

	return mmVerifyRefreshToken
}

// ExpectTokenStringParam1 sets up expected param tokenString for Manager.VerifyRefreshToken
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) ExpectTokenStringParam1(tokenString string) *mJWTManagerMockVerifyRefreshToken {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by Set")
	}

	if mmVerifyRefreshToken.defaultExpectation == nil {
		mmVerifyRefreshToken.defaultExpectation = &JWTManagerMockVerifyRefreshTokenExpectation{}
	}

	if mmVerifyRefreshToken.defaultExpectation.params != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by Expect")
	}

	if mmVerifyRefreshToken.defaultExpectation.paramPtrs == nil {
		mmVerifyRefreshToken.defaultExpectation.paramPtrs = &JWTManagerMockVerifyRefreshTokenParamPtrs{}
	}
	mmVerifyRefreshToken.defaultExpectation.paramPtrs.tokenString = &tokenString
	mmVerifyRefreshToken.defaultExpectation.expectationOrigins.originTokenString = minimock.CallerInfo(1)

	return mmVerifyRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the Manager.VerifyRefreshToken
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Inspect(f func(tokenString string)) *mJWTManagerMockVerifyRefreshToken {
	if mmVerifyRefreshToken.mock.inspectFuncVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("Inspect function is already set for JWTManagerMock.VerifyRefreshToken")
	}

	mmVerifyRefreshToken.mock.inspectFuncVerifyRefreshToken = f

	return mmVerifyRefreshToken
}

// Return sets up results that will be returned by Manager.VerifyRefreshToken
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Return(cp1 *Claims, err error) *JWTManagerMock {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by Set")
	}

	if mmVerifyRefreshToken.defaultExpectation == nil {
		mmVerifyRefreshToken.defaultExpectation = &JWTManagerMockVerifyRefreshTokenExpectation{mock: mmVerifyRefreshToken.mock}
	}
	mmVerifyRefreshToken.defaultExpectation.results = &JWTManagerMockVerifyRefreshTokenResults{cp1, err}
	mmVerifyRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmVerifyRefreshToken.mock
}

// Set uses given function f to mock the Manager.VerifyRefreshToken method
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Set(f func(tokenString string) (cp1 *Claims, err error)) *JWTManagerMock {
	if mmVerifyRefreshToken.defaultExpectation != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("Default expectation is already set for the Manager.VerifyRefreshToken method")
	}

	if len(mmVerifyRefreshToken.expectations) > 0 {
		mmVerifyRefreshToken.mock.t.Fatalf("Some expectations are already set for the Manager.VerifyRefreshToken method")
	}

	mmVerifyRefreshToken.mock.funcVerifyRefreshToken = f
	mmVerifyRefreshToken.mock.funcVerifyRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmVerifyRefreshToken.mock
}

// When sets expectation for the Manager.VerifyRefreshToken which will trigger the result defined by the following
// Then helper
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) When(tokenString string) *JWTManagerMockVerifyRefreshTokenExpectation {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("JWTManagerMock.VerifyRefreshToken mock is already set by Set")
	}

	expectation := &JWTManagerMockVerifyRefreshTokenExpectation{
		mock:               mmVerifyRefreshToken.mock,
		params:             &JWTManagerMockVerifyRefreshTokenParams{tokenString},
		expectationOrigins: JWTManagerMockVerifyRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmVerifyRefreshToken.expectations = append(mmVerifyRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up Manager.VerifyRefreshToken return parameters for the expectation previously defined by the When method
func (e *JWTManagerMockVerifyRefreshTokenExpectation) Then(cp1 *Claims, err error) *JWTManagerMock {
	e.results = &JWTManagerMockVerifyRefreshTokenResults{cp1, err}
	return e.mock
}

// Times sets number of times Manager.VerifyRefreshToken should be invoked
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Times(n uint64) *mJWTManagerMockVerifyRefreshToken {
	if n == 0 {
		mmVerifyRefreshToken.mock.t.Fatalf("Times of JWTManagerMock.VerifyRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmVerifyRefreshToken.expectedInvocations, n)
	mmVerifyRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmVerifyRefreshToken
}

func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) invocationsDone() bool {
	if len(mmVerifyRefreshToken.expectations) == 0 && mmVerifyRefreshToken.defaultExpectation == nil && mmVerifyRefreshToken.mock.funcVerifyRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmVerifyRefreshToken.mock.afterVerifyRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmVerifyRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// VerifyRefreshToken implements Manager
func (mmVerifyRefreshToken *JWTManagerMock) VerifyRefreshToken(tokenString string) (cp1 *Claims, err error) {
	mm_atomic.AddUint64(&mmVerifyRefreshToken.beforeVerifyRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmVerifyRefreshToken.afterVerifyRefreshTokenCounter, 1)

	mmVerifyRefreshToken.t.Helper()

	if mmVerifyRefreshToken.inspectFuncVerifyRefreshToken != nil {
		mmVerifyRefreshToken.inspectFuncVerifyRefreshToken(tokenString)
	}

	mm_params := JWTManagerMockVerifyRefreshTokenParams{tokenString}

	// Record call args
	mmVerifyRefreshToken.VerifyRefreshTokenMock.mutex.Lock()
	mmVerifyRefreshToken.VerifyRefreshTokenMock.callArgs = append(mmVerifyRefreshToken.VerifyRefreshTokenMock.callArgs, &mm_params)
	mmVerifyRefreshToken.VerifyRefreshTokenMock.mutex.Unlock()

	for _, e := range mmVerifyRefreshToken.VerifyRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := JWTManagerMockVerifyRefreshTokenParams{tokenString}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.tokenString != nil && !minimock.Equal(*mm_want_ptrs.tokenString, mm_got.tokenString) {
				mmVerifyRefreshToken.t.Errorf("JWTManagerMock.VerifyRefreshToken got unexpected parameter tokenString, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.expectationOrigins.originTokenString, *mm_want_ptrs.tokenString, mm_got.tokenString, minimock.Diff(*mm_want_ptrs.tokenString, mm_got.tokenString))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmVerifyRefreshToken.t.Errorf("JWTManagerMock.VerifyRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmVerifyRefreshToken.t.Fatal("No results are set for the JWTManagerMock.VerifyRefreshToken")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmVerifyRefreshToken.funcVerifyRefreshToken != nil {
		return mmVerifyRefreshToken.funcVerifyRefreshToken(tokenString)
	}
	mmVerifyRefreshToken.t.Fatalf("Unexpected call to JWTManagerMock.VerifyRefreshToken. %v", tokenString)
	return
}

// VerifyRefreshTokenAfterCounter returns a count of finished JWTManagerMock.VerifyRefreshToken invocations
func (mmVerifyRefreshToken *JWTManagerMock) VerifyRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyRefreshToken.afterVerifyRefreshTokenCounter)
}

// VerifyRefreshTokenBeforeCounter returns a count of JWTManagerMock.VerifyRefreshToken invocations
func (mmVerifyRefreshToken *JWTManagerMock) VerifyRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyRefreshToken.beforeVerifyRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to JWTManagerMock.VerifyRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmVerifyRefreshToken *mJWTManagerMockVerifyRefreshToken) Calls() []*JWTManagerMockVerifyRefreshTokenParams {
	mmVerifyRefreshToken.mutex.RLock()

	argCopy := make([]*JWTManagerMockVerifyRefreshTokenParams, len(mmVerifyRefreshToken.callArgs))
	copy(argCopy, mmVerifyRefreshToken.callArgs)

	mmVerifyRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockVerifyRefreshTokenDone returns true if the count of the VerifyRefreshToken invocations corresponds
// the number of defined expectations
func (m *JWTManagerMock) MinimockVerifyRefreshTokenDone() bool {
	if m.VerifyRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.VerifyRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.VerifyRefreshTokenMock.invocationsDone()
}

// MinimockVerifyRefreshTokenInspect logs each unmet expectation
func (m *JWTManagerMock) MinimockVerifyRefreshTokenInspect() {
	for _, e := range m.VerifyRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterVerifyRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterVerifyRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyRefreshTokenMock.defaultExpectation != nil && afterVerifyRefreshTokenCounter < 1 {
		if m.VerifyRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyRefreshToken at\n%s", m.VerifyRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to JWTManagerMock.VerifyRefreshToken at\n%s with params: %#v", m.VerifyRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.VerifyRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyRefreshToken != nil && afterVerifyRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to JWTManagerMock.VerifyRefreshToken at\n%s", m.funcVerifyRefreshTokenOrigin)
	}

	if !m.VerifyRefreshTokenMock.invocationsDone() && afterVerifyRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to JWTManagerMock.VerifyRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.VerifyRefreshTokenMock.expectedInvocations), m.VerifyRefreshTokenMock.expectedInvocationsOrigin, afterVerifyRefreshTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *JWTManagerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAccessTokenTTLInspect()

			m.MinimockGenerateAccessTokenInspect()

			m.MinimockGenerateRefreshTokenInspect()

			m.MinimockRefreshTokenTTLInspect()

			m.MinimockVerifyAccessTokenInspect()

			m.MinimockVerifyRefreshTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *JWTManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *JWTManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAccessTokenTTLDone() &&
		m.MinimockGenerateAccessTokenDone() &&
		m.MinimockGenerateRefreshTokenDone() &&
		m.MinimockRefreshTokenTTLDone() &&
		m.MinimockVerifyAccessTokenDone() &&
		m.MinimockVerifyRefreshTokenDone()
}
